from celery.schedules import crontab


# CENTRY CONFIGURATION
CENTRY_CLIENT_ID = ''
CENTRY_SECRET = ''

# CSV CONFIG
CSV_URL = ''
CSV_DELIMITER = ';'
SKU_HEADER = ''
STOCK_HEADER = ''
NORMAL_PRICE_HEADER = ''
OFFER_PRICE_HEADER = ''

# INFO SYNCRONIZATION CONFIG
PRICES_UPDATE_TIME = crontab(minute='*/3')
STOCKS_UPDATE_TIME = crontab(minute='*/3')
UPDATE_IF_LOCAL_STOCK_NULL = False
UPDATE_WITH_MAX_PRICE = False
