# Generated by Django 2.2.4 on 2019-08-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_pos', models.IntegerField()),
                ('stock_pos', models.IntegerField()),
                ('price_pos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=128)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('last_stock_reported_centry', models.IntegerField()),
                ('last_price_reported_centry', models.FloatField()),
                ('id_product_centry', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('updated_at', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
    ]
