# Generated by Django 2.2.4 on 2019-08-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvInfoRetriever', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_product_centry',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_price_reported_centry',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_stock_reported_centry',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True),
        ),
    ]
