# Generated by Django 2.2.4 on 2019-08-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvInfoRetriever', '0003_auto_20190826_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_product_centry',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_price_reported_centry',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_stock_reported_centry',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
