# Generated by Django 2.2.4 on 2019-09-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvInfoRetriever', '0004_auto_20190827_0008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportConfig',
        ),
    ]
